"""Quality validation tests for real pipeline output files.

Reads the JSON outputs generated by the integration tests from mock_output/ and
asserts structural invariants that must hold for any high-quality pipeline run.

These tests are SKIPPED when the files are absent — mock_output/ is git-ignored
and only exists after running the integration tests locally.

To populate the files:
    pytest tests/integration/test_real_pipeline.py -m slow -s
    pytest tests/integration/test_diarization_speaker_detection.py -m slow -s
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).parent.parent.parent
_BLOOD_JSON = _REPO_ROOT / "mock_output" / "BLOOD_liquidity_Captions_V2.json"
_DIAR_JSON = _REPO_ROOT / "mock_output" / "diarization" / "ABSOLUTELYNOT_Sequence02.json"

# ── Fixtures ──────────────────────────────────────────────────────────────────


def _load(path: Path) -> dict:
    """Load JSON; skip the test module if the file is absent."""
    if not path.exists():
        pytest.skip(f"Mock output not found (run integration tests first): {path}")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


@pytest.fixture(scope="module")
def blood_doc():
    return _load(_BLOOD_JSON)


@pytest.fixture(scope="module")
def diar_doc():
    return _load(_DIAR_JSON)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _check_doc_invariants(doc: dict, label: str) -> None:
    """Assert universal invariants that must hold for any TranscriptDocument JSON."""
    segs = doc["segments"]
    duration = doc["duration_s"]
    pr = doc["processing_report"]

    # ── Basic structure ────────────────────────────────────────────────────
    assert isinstance(segs, list), f"{label}: segments must be a list"
    assert duration > 0, f"{label}: duration_s must be positive"
    assert isinstance(pr["errors"], list), f"{label}: errors must be a list"

    # ── Timestamp ordering and bounds ──────────────────────────────────────
    for i, s in enumerate(segs):
        assert s["start"] >= 0, f"{label} seg{i}: start < 0"
        assert s["end"] > s["start"], f"{label} seg{i}: end <= start"
        assert s["end"] <= duration + 0.5, (
            f"{label} seg{i}: end={s['end']:.3f} > duration={duration:.3f} + tolerance"
        )

    # ── Segment ordering by start ──────────────────────────────────────────
    starts = [s["start"] for s in segs]
    assert starts == sorted(starts), f"{label}: segments are not sorted by start time"

    # ── Confidence in [0, 1] ───────────────────────────────────────────────
    for i, s in enumerate(segs):
        c = s["confidence"]
        assert 0.0 <= c <= 1.0, f"{label} seg{i}: confidence={c} out of [0,1]"

    # ── Word timestamps ────────────────────────────────────────────────────
    for i, s in enumerate(segs):
        for j, w in enumerate(s.get("words") or []):
            assert w["end"] > w["start"], (
                f"{label} seg{i} word{j}: end={w['end']} <= start={w['start']}"
            )
            assert 0.0 <= w["confidence"] <= 1.0, (
                f"{label} seg{i} word{j}: confidence={w['confidence']} out of [0,1]"
            )

    # ── Silence spans ──────────────────────────────────────────────────────
    for i, sp in enumerate(doc.get("silence_spans", [])):
        assert sp["duration_ms"] > 0, f"{label} span{i}: duration_ms <= 0"
        assert sp["end"] > sp["start"], f"{label} span{i}: end <= start"


def _check_emotion_invariants(doc: dict, label: str) -> None:
    """Assert emotion-specific invariants for every segment that has an emotion score."""
    for i, s in enumerate(doc["segments"]):
        e = s.get("emotion")
        if e is None:
            continue
        dist = e["label_distribution"]
        assert isinstance(dist, dict), f"{label} seg{i}: label_distribution is not a dict"
        assert len(dist) > 0, f"{label} seg{i}: label_distribution is empty"

        # All values must be floats in [0,1]
        for lbl, prob in dist.items():
            assert isinstance(prob, (int, float)), (
                f"{label} seg{i}: label_distribution[{lbl!r}] is not a number"
            )
            assert 0.0 <= float(prob) <= 1.0 + 1e-6, (
                f"{label} seg{i}: probability {prob} for label {lbl!r} out of [0,1]"
            )

        # Probabilities must sum to approximately 1.0 (softmax output)
        total = sum(float(v) for v in dist.values())
        assert abs(total - 1.0) < 0.02, (
            f"{label} seg{i}: label_distribution sums to {total:.6f}, expected ~1.0"
        )

        # Confidence must be in [0,1]
        conf = e["confidence"]
        assert 0.0 <= float(conf) <= 1.0, f"{label} seg{i}: emotion confidence={conf} out of [0,1]"

        # backend_name must be a non-empty string
        assert isinstance(e["backend_name"], str) and e["backend_name"], (
            f"{label} seg{i}: emotion backend_name missing"
        )


# ── BLOOD pipeline output (no diarization, with emotion) ─────────────────────


class TestBloodOutputQuality:
    def test_universal_invariants(self, blood_doc):
        _check_doc_invariants(blood_doc, "BLOOD")

    def test_at_least_one_segment(self, blood_doc):
        assert len(blood_doc["segments"]) > 0

    def test_all_segments_have_words(self, blood_doc):
        segs_with_words = [s for s in blood_doc["segments"] if s.get("words")]
        total = len(blood_doc["segments"])
        assert len(segs_with_words) > 0, "No segments have word-level timestamps"
        assert len(segs_with_words) / total >= 0.7, (
            f"Only {len(segs_with_words)}/{total} segments have word-level timestamps"
        )

    def test_word_alignment_backend_set(self, blood_doc):
        for i, s in enumerate(blood_doc["segments"]):
            for j, w in enumerate(s.get("words") or []):
                assert w.get("alignment_backend"), f"seg{i} word{j} missing alignment_backend"

    def test_emotion_quality(self, blood_doc):
        emotion_segs = [s for s in blood_doc["segments"] if s.get("emotion")]
        assert len(emotion_segs) > 0, "No segments have emotion scores"
        _check_emotion_invariants(blood_doc, "BLOOD")

    def test_emotion_labels_are_iemocap(self, blood_doc):
        """All emotion labels must be from the IEMOCAP label set."""
        expected_labels = {"neu", "ang", "hap", "sad"}
        for i, s in enumerate(blood_doc["segments"]):
            e = s.get("emotion")
            if e:
                labels = set(e["label_distribution"].keys())
                unexpected = labels - expected_labels
                assert not unexpected, (
                    f"seg{i}: unexpected emotion labels {unexpected}. "
                    f"Expected IEMOCAP labels: {expected_labels}"
                )

    def test_provenance_records_all_stages(self, blood_doc):
        """Provenance must record VAD, ASR, alignment, and emotion stages."""
        prov_stages = {s["stage"] for s in (blood_doc.get("provenance", {}).get("stages") or [])}
        for required in ("vad", "asr", "alignment", "emotion"):
            assert required in prov_stages, (
                f"Provenance missing stage '{required}'. Recorded: {sorted(prov_stages)}"
            )

    def test_processing_report_has_timings(self, blood_doc):
        timings = blood_doc["processing_report"]["stage_timings"]
        for stage in ("decode", "vad", "asr", "alignment"):
            assert stage in timings and timings[stage] > 0, (
                f"Missing or zero timing for stage '{stage}'"
            )

    def test_rtf_is_positive_and_finite(self, blood_doc):
        rtf = blood_doc["processing_report"]["real_time_factor"]
        assert rtf > 0, "RTF must be positive"
        assert math.isfinite(rtf), "RTF must be finite"

    def test_language_detected(self, blood_doc):
        assert blood_doc["language"] is not None, "Language must be detected"
        assert len(blood_doc["language"]) == 2, "Language must be an ISO 639-1 code"


# ── ABSOLUTELYNOT diarization output (diarization + emotion) ─────────────────


class TestDiarizationOutputQuality:
    def test_universal_invariants(self, diar_doc):
        _check_doc_invariants(diar_doc, "ABSOLUTELYNOT")

    def test_multiple_speakers_detected(self, diar_doc):
        speakers = {s["speaker"] for s in diar_doc["segments"] if s.get("speaker")}
        assert len(speakers) >= 2, f"Expected >=2 speakers; got {len(speakers)}: {sorted(speakers)}"

    def test_speaker_label_format(self, diar_doc):
        for i, s in enumerate(diar_doc["segments"]):
            sp = s.get("speaker")
            if sp is not None:
                assert sp.startswith("SPEAKER_"), (
                    f"seg{i}: speaker label '{sp}' does not match SPEAKER_NN format"
                )

    def test_speaker_coverage_above_threshold(self, diar_doc):
        labeled = sum(1 for s in diar_doc["segments"] if s.get("speaker"))
        total = len(diar_doc["segments"])
        coverage = labeled / total
        assert coverage >= 0.70, (
            f"Speaker coverage {labeled}/{total} ({coverage:.0%}) below 70% threshold"
        )

    def test_emotion_quality(self, diar_doc):
        emotion_segs = [s for s in diar_doc["segments"] if s.get("emotion")]
        assert len(emotion_segs) > 0, "No segments have emotion scores"
        _check_emotion_invariants(diar_doc, "ABSOLUTELYNOT")

    def test_emotion_labels_are_iemocap(self, diar_doc):
        expected_labels = {"neu", "ang", "hap", "sad"}
        for i, s in enumerate(diar_doc["segments"]):
            e = s.get("emotion")
            if e:
                labels = set(e["label_distribution"].keys())
                unexpected = labels - expected_labels
                assert not unexpected, (
                    f"seg{i}: unexpected labels {unexpected}; expected {expected_labels}"
                )

    def test_all_eligible_segments_have_emotion(self, diar_doc):
        """Segments >= 0.5s (the SpeechBrain minimum) must have emotion scores."""
        eligible = [s for s in diar_doc["segments"] if (s["end"] - s["start"]) >= 0.5]
        with_emotion = [s for s in eligible if s.get("emotion")]
        assert len(with_emotion) == len(eligible), (
            f"Only {len(with_emotion)}/{len(eligible)} eligible segments scored"
        )

    def test_provenance_records_all_stages(self, diar_doc):
        prov_stages = {s["stage"] for s in (diar_doc.get("provenance", {}).get("stages") or [])}
        for required in ("vad", "asr", "alignment", "diarization", "emotion"):
            assert required in prov_stages, (
                f"Provenance missing stage '{required}'. Recorded: {sorted(prov_stages)}"
            )

    def test_word_alignment_backend_set(self, diar_doc):
        for i, s in enumerate(diar_doc["segments"]):
            for j, w in enumerate(s.get("words") or []):
                assert w.get("alignment_backend"), f"seg{i} word{j} missing alignment_backend"

    def test_processing_report_no_errors(self, diar_doc):
        errors = diar_doc["processing_report"]["errors"]
        assert errors == [], f"Unexpected pipeline errors: {errors}"

    def test_rtf_is_positive(self, diar_doc):
        rtf = diar_doc["processing_report"]["real_time_factor"]
        assert rtf > 0
        assert math.isfinite(rtf)
